spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/final_board
    username: root
    password: 0000

  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/public/
        - classpath:/resources/
        - classpath:/META-INF/resources/

decorator:
  datasource:
    enabled: false

mybatis:
  mapper-locations: classpath:repository/*.xml
  type-aliases-package: com.juny.finalboard

resources:
  image-resource: "file:/Users/jijunhyuk/JunyProjects/ebrainsoft/images/"
  attachment-resource: "file:/Users/jijunhyuk/JunyProjects/ebrainsoft/attachments/"